apiVersion: apps/v1

kind: Deployment

metadata:
  name: deployment-app

spec:
  replicas: {{ .Values.deployment.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Values.deployment.app-label }}

  template:
    metadata:
      name: {{ .Values.deployment.app-label }}
      labels:
        # selector의 matchLabels과 동일함.
        app: {{ .Values.deployment.app-label }}
    spec:
      containers:
        - name: my-nginx
          image: {{ .Values.deployment.my-nginx.image }}
          ports:
            - containerPort: {{ .Values.deployment.my-nginx.containerPort }}
        - name: flask-gunicorn
          image: {{ .Values.deployment.flask-gunicorn.image }}
          ports:
            - containerPort: {{ .Values.deployment.flask-gunicorn.containerPort }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 4
