apiVersion: v1

kind: Service

metadata:
  name: service-app

spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: {{ .Values.deployment.app-label }}
  ports:
    - name: node-port
      port: 8080
      targetPort: {{ .Values.deployment.my-nginx.containerPort }}
      nodePort: 30080
