apiVersion: v1

kind: Service

metadata:
  name: service-app

spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: nginx-gunicorn-flask
  ports:
    - name: node-port
      port: 8080
      targetPort: 80
      nodePort: 30080
