FROM python:3.7.3-stretch

# Install hadolint for linting Dockerfile
RUN wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 --no-check-certificate
RUN chmod +x ./hadolint

CMD /bin/bash
