# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


deployment:
  replicaCount: 6
  app-label: nginx-gunicorn-flask

  my-nginx:
  # use --set option when deploying new version of image
    image: kde6260/my-nginx:stable
    containerPort: 80

  flask-gunicorn:
    # use --set option when deploying new version of image
    image: kde6260/flask-gunicorn:0.0.1
    containerPort: 9090


service:
  port: 8080
  nodePort: 30080
