apiVersion: apps/v1

kind: Deployment

metadata:
  name: deployment-flask-wsgi

spec:
  replicas: 6

  selector:
    matchLabels:
      app: flask-wsgi

  revisionHistoryLimit: 5

  template:
    metadata:
      name: pod-flask-wsgi
      labels:
        app: flask-wsgi
    spec:
      containers:
        - name: flask-wsgi
          image: kde6260/flask-wsgi:lazy-apps
          ports:
            - containerPort: 9090

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 4
