apiVersion: apps/v1

kind: Deployment

metadata:
  name: deployment-nginx

spec:
  replicas: 12

  selector:
    matchLabels:
      app: my-nginx

  revisionHistoryLimit: 5

  template:
    metadata:
      name: pod-my-nginx
      labels:
        # selector의 matchLabels과 동일함.
        app: my-nginx
    spec:
      containers:
        - name: my-nginx
          image: kde6260/my-nginx:0.0.4
          ports:
            - containerPort: 80

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 4
