Description:
 ALB distributing traffic to instances in private subnets via NAT in public subnets.


Parameters:
  ServiceName:
    Type: String


Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 10
      Subnets:
        - Fn::ImportValue: !Sub ${ServiceName}-PublicSubnet1
        - Fn::ImportValue: !Sub ${ServiceName}-PublicSubnet2
      SecurityGroups:
        - Fn::ImportValue: !Sub ${ServiceName}-SecurityGroupForLB

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      # HealthCheckIntervalSeconds should be bigger than HealthCheckTimeoutSeconds.
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckPort: 30080
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 15
      # if load balancer requests 5 times to target and it returns OK 5 times, it is considered healthy.
      HealthyThresholdCount: 5
      # if load balancer requests 5 times to target and it returns Internal Server Error or does not respond 5 times,
      # it is considered unhealthy.
      UnhealthyThresholdCount: 5
      Port: 30080
      Protocol: HTTP
      Matcher:
        HttpCode: 200
      VpcId:
        Fn::ImportValue: !Sub ${ServiceName}-VPC

  LBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  LBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      Conditions:
        - Field: path-pattern
          Values: [/]
      ListenerArn: !Ref LBListener
      Priority: 1


Outputs:
  LoadBalancer:
    Value: !Ref LoadBalancer
    Export:
      Name: !Sub ${ServiceName}-LoadBalancer

  LoadBalancerDNSname:
    Value: !GetAtt LoadBalancer.DNSName
    Export:
      Name: !Sub ${ServiceName}-LoadBalancerDNSname

  LoadBalancerHZID:
    Value: !GetAtt LoadBalancer.CanonicalHostedZoneID
    Export:
      Name: !Sub ${ServiceName}-LoadBalancerHZID

  TargetGroup:
    Value: !Ref TargetGroup
    Export:
      Name: !Sub ${ServiceName}-LoadBalancerTargetGroup
