Description:
  VPC & subnets for Kubernetess cluster.


Parameters:
  ServiceName:
    Description: service's name
    Type: String

  VpcCIDR:
    Description: IP range (CIDR notation) for VPC
    Type: String

  PubSub1CIDR:
    Description: CIDR block for NAT gateway in public subnet
    Type: String

  PubSub2CIDR:
    Description: CIDR block for NAT gateway in public subnet
    Type: String

  PubSubMasterCIDR:
    Description: CIDR block for NAT gateway in public subnet
    Type: String

  PriSubWorker1CIDR:
    Description: CIDR block for worker nodes in private subnet
    Type: String

  PriSubWorker2CIDR:
    Description: CIDR block for worker nodes in private subnet
    Type: String

  PriSubMasterCIDR:
    Description: CIDR block for master node private subnet
    Type: String


Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Ref ServiceName

  PubSub1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: us-west-2b
      CidrBlock: !Ref PubSub1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub PublicSubnet1 for ${ServiceName}

  PubSub2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: us-west-2c
      CidrBlock: !Ref PubSub2CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub PublicSubnet2 for ${ServiceName}

  PubSubMaster:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: us-west-2a
      CidrBlock: !Ref PubSubMasterCIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub PublicSubnetMaster for ${ServiceName}

  PriSubWorker1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: us-west-2b
      CidrBlock: !Ref PriSubWorker1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub PrivateSubnet1 for workers in ${ServiceName}

  PriSubWorker2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: us-west-2c
      CidrBlock: !Ref PriSubWorker2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub PrivateSubnet2 for workers in ${ServiceName}

  PriSubMaster:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: us-west-2a
      CidrBlock: !Ref PriSubMasterCIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub PrivateSubnetMaster in ${ServiceName}


Outputs:
  VPC:
    Value: !Ref VPC
    Export:
      Name: !Sub ${ServiceName}-VPC

  VpcCIDR:
    Value: !GetAtt VPC.CidrBlock
    Export:
      Name: !Sub ${ServiceName}-VpcCIDR

  PubSub1:
    Value: !Ref PubSub1
    Export:
      Name: !Sub ${ServiceName}-PublicSubnet1

  PubSub2:
    Value: !Ref PubSub2
    Export:
      Name: !Sub ${ServiceName}-PublicSubnet2

  PubSubMaster:
    Value: !Ref PubSubMaster
    Export:
      Name: !Sub ${ServiceName}-PublicSubnetMaster

  PriSub1:
    Value: !Ref PriSubWorker1
    Export:
      Name: !Sub ${ServiceName}-PrivateSubnet1

  PriSub2:
    Value: !Ref PriSubWorker2
    Export:
      Name: !Sub ${ServiceName}-PrivateSubnet2

  PriSubMaster:
    Value: !Ref PriSubMaster
    Export:
      Name: !Sub ${ServiceName}-PrivateSubnetMaster
