version: 2
jobs:
  build:
    working_directory: ~/uc-k8s-cluster
    docker:
      - image: kde6260/circleci-agent:0.0.2

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "app/requirements.txt" }}
            - v1-dependencies-

      - run:
          name: Set virtualenv
          command: |
            python -m venv venv
            . venv/bin/activate

      - run:
          name: Lint Dockerfile
          command: |
            hadolint docker/app/Dockerfile --ignore DL3013
            hadolint docker/nginx/Dockerfile --ignore DL3013

      - run:
          name: Install dependencies
          command: pip install -r app/requirements.txt

      - run:
          name: Lint Python code
          command: pylint --disable=R,C,W1203 app/app.py

      - run:
          name: Execute Pytest
          command: |
            export FLASK_APP=app/app:flask_app
            flask run --port 5000 &
            pytest app/tests.py

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "app/requirements.txt" }}
