apiVersion: v1
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
        multi_accept on;
    }

    http {
        log_format main '$remote_addr - $remote_user [$time_local]  $status '
                        '"$request" $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        error_log  /var/log/nginx/error.log warn;
        access_log /var/log/nginx/access.log main;

        upstream flask_server {
            server service-flask-wsgi:9090;
            keepalive 512;
            keepalive_timeout 5;
        }
        server {
            listen 80;
            server_name service-flask-wsgi;

            location / {
                include /etc/nginx/uwsgi_params;
                uwsgi_pass flask_server;
            }
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-11T05:46:27Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:nginx.conf: {}
    manager: kubectl
    operation: Update
    time: "2020-04-11T05:46:27Z"
  name: nginx-configuration
  namespace: ingress-nginx
  resourceVersion: "554851"
  selfLink: /api/v1/namespaces/ingress-nginx/configmaps/nginx-configuration
  uid: 35dd71a6-bc76-4c52-ad54-529bacb4408d
