apiVersion: apps/v1

kind: Deployment

metadata:
  name: deployment-nginx

spec:
  replicas: 6

  selector:
    matchLabels:
      app: my-nginx

  template:
    metadata:
      name: pod-my-nginx
      labels:
        # selector의 matchLabels과 동일함.
        app: my-nginx
    spec:
      containers:
        - name: my-nginx
          image: nginx:1.17.10-alpine
          ports:
            - containerPort: 80

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 4
