apiVersion: apps/v1

kind: Deployment

metadata:
  name: deployment-app
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.deployment.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Values.deployment.appLabel }}

  template:
    metadata:
      name: {{ .Values.deployment.appLabel }}
      labels:
        # selector의 matchLabels과 동일함.
        app: {{ .Values.deployment.appLabel }}
    spec:
      containers:
        - name: my-nginx
          image: {{ .Values.deployment.myNginx.image }}
          ports:
            - containerPort: {{ .Values.deployment.myNginx.containerPort }}
        - name: flask-gunicorn
          image: {{ .Values.deployment.flaskGunicorn.image }}
          ports:
            - containerPort: {{ .Values.deployment.flaskGunicorn.containerPort }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 4
