apiVersion: v1

kind: Service

metadata:
  name: service-app

spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: {{ .Values.deployment.appLabel }}
  ports:
    - name: node-port
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.myNginx.containerPort }}
      nodePort: {{ .Values.service.nodePort }}
