kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  use-proxy-protocol: "false"
  use-forwarded-headers: "true"
  proxy-real-ip-cidr: "0.0.0.0/0" # restrict this to the IP addresses of ELB
  nginx.conf: |
    user root;
    worker_processes auto;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
        multi_accept on;
    }

    http {
        log_format main '$remote_addr - $remote_user [$time_local]  $status '
                        '"$request" $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        error_log  /var/log/nginx/error.log warn;
        access_log /var/log/nginx/access.log main;

        upstream flask_server {
            server service-flask-wsgi:9090;
            keepalive 512;
            keepalive_timeout 5;
        }
        server {
            listen 80;
            server_name service-flask-wsgi;

            location / {
                include /etc/nginx/uwsgi_params;
                uwsgi_pass flask_server;
            }
        }
    }
---
